apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstack-actions-runner.fullname" . }}
  labels:
    {{- include "openstack-actions-runner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "openstack-actions-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.yml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/gcloud-service-account: {{ include (print $.Template.BasePath "/google-service-account.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openstack-actions-runner.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openstack-actions-runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.manager.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["uvicorn"]
        args: ["srcs.web.app:app", "--host", "0.0.0.0", "--port", "80"]
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: http
          containerPort: 80
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.fullnameOverride }}
              key: redis-password
        - name: SETTING_FILE
          value: /app/config/settings.yml
        {{- if .Values.gcloudServiceAccount }}
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/service_account/credentials.json
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        - secretRef:
            name: {{ .Release.Name }}-auth
        volumeMounts:
        - name: config
          mountPath: /app/config
        {{- if .Values.gcloudServiceAccount }}
        - name: gcloud-service-account
          mountPath: /secrets/service_account
          readOnly: true
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-settings
      {{- if .Values.gcloudServiceAccount }}
      - name: gcloud-service-account
        secret:
          secretName: '{{ .Release.Name }}-gcloud-service-account'
          items:
          - key: credentials.json
            path: credentials.json
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
