apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings
data:
  settings.yml: |-
    cloud_name: {{ .Values.cloudName }}
    cloud_config:
{{ .Values.cloudConfig | toYaml | indent 6 }}
    github_organization: {{ .Values.githubOrganization }}
    allowed_ssh_keys: {{ .Values.allowedSshKeys | toYaml | indent 6  }}
    python_config: {{ .Values.pythonConfigModule }}
    runner_pool:
{{ .Values.runnerPool | toYaml | indent 6 }}
    extra_runner_timer:
{{ .Values.extraRunnerTimer | toYaml | indent 6 }}
    timeout_runner_timer:
{{ .Values.timeoutRunnerTimer | toYaml | indent 6 }}
    redis:
      host: {{ .Values.redis.fullnameOverride  }}-master
      port: {{ .Values.redis.redisPort }}
