version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python3 /app/srcs/web/app.py
    volumes:
      - "./srcs:/app/srcs"
      - ./test_settings.yml:/app/test_settings.yml
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=0
      - PYTHONIOENCODING=UTF-8
      - SETTING_FILE=/app/test_settings.yml
    ports:
      - "8080:8080"
  redis:
    image: "redis:alpine"
