apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-manager
  labels: {}
spec:
  selector: {}
  template:
    metadata: {}
    spec:
      serviceAccountName: default
      containers:
        - args:
            - 'srcs.web.app:app'
            - '--host'
            - 0.0.0.0
            - '--port'
            - '80'
          command:
            - uvicorn
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: redis-secrets
            - name: SETTING_FILE
              value: /app/config/settings.yaml
          envFrom:
            - configMapRef:
                name: runner-manager-config
            - secretRef:
                name: runner-manager-secrets
          image: 'ghcr.io/scality/runner-manager:0.6.3'
          imagePullPolicy: IfNotPresent
          name: runner-manager
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
          securityContext: {}
          volumeMounts:
            - mountPath: /app/config
              name: config
      volumes:
        - name: config
          configMap:
            name: runner-manager-settings
