apiVersion: v1
kind: Service
metadata:
  name: runner-manager
  labels: {}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: runner-manager
  selector: {}
