{{- if .Values.deployment.ingress.basicAuthCreds }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-basic-auth
data:
  auth: {{ .Values.deployment.ingress.basicAuthCreds | b64enc }}
{{- end }}
