---
name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 8 * * 1' # Monday - 8am - UTC

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v1
    with:
      name: runner-manager
      namespace: scality
  trivy:
    needs: build
    name: Trivy Vulnerability Scan for Code
    uses: scality/workflows/.github/workflows/trivy.yaml@v1
    with:
      name: runner-manager
      namespace: scality
